In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!pip install transformers==4.3.3
!pip install stop_words
!pip install symspellpy
!pip install language_detector 
!pip install cached_property
!pip install sentencepiece
!pip install config
!pip install umap
!pip install sentence-transformers==0.4.1
!pip install nltk
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

     |████████████████████████████████| 1.9 MB 5.5 MB/s 
     |████████████████████████████████| 895 kB 38.0 MB/s 
     |████████████████████████████████| 3.3 MB 48.5 MB/s 
  Created wheel for stop-words: filename=stop_words-2018.7.23-py3-none-any.whl size=32911 sha256=13e0f7e2cf9058eb16b6f3ab0e5e6c32ab240965a1e1657e40b7657078b71e91
  Stored in directory: /root/.cache/pip/wheels/fb/86/b2/277b10b1ce9f73ce15059bf6975d4547cc4ec3feeb651978e9
Successfully built stop-words
     |████████████████████████████████| 2.6 MB 5.4 MB/s 
     |████████████████████████████████| 125 kB 65.5 MB/s 
  Created wheel for language-detector: filename=language_detector-5.0.2-py3-none-any.whl size=7054 sha256=9541bffc4de3d08e1f53915e4e80ad287340713d64f4c2630e048985a2ec5740
  Stored in directory: /root/.cache/pip/wheels/12/40/73/a0765d65e793332b79dfe6c34c713e7c0066ea785191b3f50a
Successfully built language-detector
     |████████████████████████████████| 1.2 MB 5.1 MB/s 
  Created wheel for umap: filename=umap-0

True

In [4]:
root_path = "/content/drive/MyDrive/SCHOOL/PhD/Code/context-encoder-v2"
import sys, os
import config

config.root_path = os.path.abspath(root_path)
sys.path.insert(0, config.root_path)

In [5]:
import tensorflow as tf

from tensorflow.python import keras
import json
import pandas as pd
import numpy as np
import os

from src.encoders.context_encoder_ldabert_2 import ContextEncoderComplex, ContextEncoderSimple
from src.dataset.ldabert_2 import LDABERT2Dataset
import transformers
import sentence_transformers

from utils.metrics import windowdiff, pk

Downloading:   0%|          | 0.00/630 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/409 [00:00<?, ?B/s]

In [6]:
tf.__version__, transformers.__version__, sentence_transformers.__version__

('2.7.0', '4.3.3', '0.4.1')

## LDA BERT 2 Dataset

In [7]:
dataset_type_to = "clinical"
dataset = LDABERT2Dataset(dataset_type=dataset_type_to,
                           pct_data=0.075,
                          max_seq_length=128,
                           max_segment_length=300,
                           augment_pct=0)

sentences, tokenized_sentences, labels = dataset.process()

# vectors_path = '../data/clinical_vectors/lda_bert_{}_{}.pkl'.format(dataset_type, len(sentences))
vectors_filename = '{}_{}.pkl'.format(dataset.pct_data, dataset.augment_pct)

saved_vectors, saved_labels, saved_tokens, saved_tokenized_sentences = dataset.get_saved_vectors("test", dataset.dataset_type, vectors_filename)

if len(saved_vectors) == 0:
    saved_vectors, saved_labels, saved_tokens, saved_tokenized_sentences = dataset.create_vectors("test", dataset.dataset_type, vectors_filename)

artificial segments False
artificial segments False


In [8]:
left_input, mid_input, right_input = dataset.format_sentences_tri_input_plus(saved_tokenized_sentences)

In [9]:
lda_left_input, lda_mid_input, lda_right_input = dataset.format_sentences_tri_input(saved_vectors)

In [10]:
saved_tokenized_sentences['input_ids'].shape, saved_vectors.shape

(TensorShape([2285, 128]), (2285, 12))

In [11]:
saved_tokens

['The arterial pulse changes as it travels from the central aorta down to the peripheral arteries ',
 'Although mean blood pressure decreases from the central aorta to the peripheral arteries  the systolic pressure increases ',
 'The pulse can be distorted and damped by reflected  resonance  or standing waves  as well as differences in the elastic properties and caliber of the peripheral arteries of the upper and lower parts of the body ',
 'The size of the normal arterial pulse is affected by the left ventricular ejection volume and the rate of ejection  as well as the elasticity or distensibility of the peripheral arteries ',
 'The greater the distance from the heart to a peripheral artery  the greater will be the distortion of the arterial pulse peripherally ',
 'Because complex factors affect the contour of the arterial pulse as it is transmitted through the arterial system  careful examination of the most central arterial pulse  the carotid  is necessary for pulse contour informat

## Model

In [12]:
lda_gamma = 15
model = ContextEncoderComplex(final_dropout=0.5,
                            dense_neurons=256,
                                  lstm_size=256,
                             lstm_dropout_percentage=0.5,
                             cnn_filters=8,
                             cnn_kernel_size=3,
                             pool_size=2,
                          gamma=lda_gamma,
                          max_sentence_length=128,
                           bert_trainable=False)
# model = ContextEncoderSimple(final_dropout=0.5,
#                             dense_neurons=256,
#                           gamma=lda_gamma,
#                           max_sentence_length=128,
#                            bert_trainable=False)

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['embeddings.position_ids']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [13]:
hash = "6YPov"
num_samples = "37412"
dataset_type_from = "wiki"
model_path = 'LDABERT2/complex/{}-{}-1-pct-1-aug_{}/no-finetune'.format(dataset_type_from, num_samples, hash)
checkpoint_filepath = '../models/{}/checkpoint'.format(model_path)
log_file = '../predictions/{}_lda-{}-{}/predictions.csv'.format(hash, lda_gamma, dataset_type_to)

In [14]:
# try:
model.load_weights(checkpoint_filepath)
# except:
#     print("No checkpoint available.")

In [15]:
model.summary()

ValueError: ignored

In [16]:
saved_tokenized_sentences

{'input_ids': <tf.Tensor: shape=(2285, 128), dtype=int32, numpy=
array([[  101,  1996, 25543, ...,     0,     0,     0],
       [  101,  2348,  2812, ...,     0,     0,     0],
       [  101,  1996,  8187, ...,     0,     0,     0],
       ...,
       [  101, 21961, 23586, ...,     0,     0,     0],
       [  101,  2035,  1997, ...,     0,     0,     0],
       [  101,  1996,  3019, ...,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2285, 128), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2285, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=in

## Inference

In [17]:
slice_size = 125
predictions_log = []

for threshold in [0.5]:
  for i in range(0, saved_vectors.shape[0]//slice_size):
      start = i*slice_size
      end = start + slice_size
      print(start, end)

      sliced_tokenized_sentences = {
          'input_ids': saved_tokenized_sentences['input_ids'][start:end],
          'token_type_ids': saved_tokenized_sentences['token_type_ids'][start:end],
          'attention_mask': saved_tokenized_sentences['attention_mask'][start:end]
      }
      sliced_vectors = saved_vectors[start:end]
      
      left_input, mid_input, right_input = dataset.format_sentences_tri_input_plus(sliced_tokenized_sentences)
      lda_left_input, lda_mid_input, lda_right_input = dataset.format_sentences_tri_input(sliced_vectors)
      
      logits = model([
          left_input, 
          mid_input, 
          right_input, 
          lda_left_input, 
          lda_mid_input, 
          lda_right_input
      ])

      logits_flattened = [float(p) for p in logits]

      predictions = [1 if float(logit) >= threshold else 0 for logit in logits_flattened]

      k = 14

      string_predictions = "".join([str(i) for i in predictions])
      string_ground_truth = "".join([str(i) for i in saved_labels[start:end]])
      print(string_predictions)
      print(string_ground_truth)
      overall_windowdiff = windowdiff(string_predictions, string_ground_truth, k)
      overall_pk = pk(string_predictions, string_ground_truth, k)

      for pred_idx, pred in enumerate(predictions):
        log = {
            "prediction": pred,
            "ground_truth": saved_labels[start:end][pred_idx],
            "text": saved_tokens[start:end][pred_idx],
            "lda_gamma": lda_gamma,
            "prediction_threshold": threshold,
            "logit": logits_flattened[pred_idx]
        }
        predictions_log.append(log)

      print("{},{},{},{}".format(overall_windowdiff, overall_pk, k, k))

0 125
sbert_output TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(125, 128, 768), dtype=float32, numpy=
array([[[-0.3993758 ,  0.7648735 ,  0.91013086, ...,  0.2152904 ,
          0.54933643, -0.09573432],
        [-1.0867796 ,  1.2284027 ,  1.182914  , ...,  0.05355093,
          0.35541114, -0.06371193],
        [-0.7298635 ,  1.2532313 ,  1.0690972 , ..., -0.00805134,
          0.4164464 , -0.12039414],
        ...,
        [-0.43710327,  0.62348884,  1.16122   , ...,  0.22209482,
          0.2894895 , -0.33569413],
        [-0.7275725 ,  0.5813997 ,  1.2508984 , ...,  0.20124438,
          0.51903504, -0.5404612 ],
        [-0.52130264,  0.6918082 ,  1.1790648 , ...,  0.12823033,
          0.32668716, -0.37061098]],

       [[ 0.82535726, -1.1223232 ,  1.0488343 , ..., -0.06074838,
         -0.40137002,  0.6455007 ],
        [ 0.7576709 , -1.4008559 ,  1.1932726 , ...,  0.15608773,
         -0.7739216 ,  0.55741626],
        [ 0.9020398 , -1.0028045 ,  1.1936674 

In [18]:
try:
  import csv
  if not os.path.exists(os.path.dirname(log_file)):
      os.makedirs(os.path.dirname(log_file))
  mode = 'a' if os.path.exists(log_file) else 'w'
  with open(log_file, mode) as csvfile:
      writer = csv.DictWriter(csvfile, fieldnames=["prediction", "ground_truth", "text", "lda_gamma", "prediction_threshold", "logit"])
      writer.writeheader()
      for data in predictions_log:
          writer.writerow(data)
except IOError:
    print("I/O error")

In [ ]:
[float(p) for p in predictions], saved_labels

([0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0],
 [1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,